name: GitHub Actions Testing
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Testing-Full-Project:
    runs-on: ubuntu-latest
    steps:
      - run: pnpm i
      - name: Instalando las dependencias
      - run: pnpm t
      - name: Lanzando tests ğŸš€
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
